### ISSUE TITLE
Thread panic when modification is unknown or placed on wrong amino acid

### ISSUE THREAD

**Issue by ArthurDeclercq** [rusteomics/mzcore#38]
Dear @douweschulte 

When I try to retrieve the annotations (in python with the python bindings) given a certain proforma sequence from a RawSpectrum object I get the following error when a modification is not know or is placed on a invalid amino acid. 

`thread '<unnamed>' panicked at rustyms-py\src\lib.rs:858:67:
called Result::unwrap() on an Err value: error: Modification incorrectly placed
Modification U:HNE is not allowed on aminoacid R index 3`

These modifications are typically either user input to Unimod or new additions, and probably not added to the repository. In this case according to Unimod R is a potential location for U:HNE. It would be nice if this could return an error instead of a thread panic so I can catch this and write a try except around, as there will always be new user uploads with specific modifications. This way I could catch this. 

Thanks in advance,
Arthur

**Comment by RalfG** [comment]
This was with v0.8.3. I noticed that with the current main branch a ValueError is indeed raised as expected. Any plans for a next release? Thanks!

**Comment by douweschulte** [comment]
I am thinking about a release quite soon. There was no need from my side for a stable release yet and with the mzdata integration and my work on the annotator I know I will make breaking changes in the coming weeks. I can think about making a release in between.

**Comment by douweschulte** [comment]
As a sidenote if there are any things you are missing from the python bindings I could add some bindings before making the release. There is a lot more available from the Rust side and because I have had no personal projects in Python with this project so I have not worked actively on the Python side a lot.

**Comment by ArthurDeclercq** [comment]
For me the most important was the error and I haven't really played around with other things but generating theoretical fragments for modifications of unknown position would also be a really helpful feature since I am working with modifications a lot

**Comment by douweschulte** [comment]
Thanks. Those fragments will be generated (if such modifications are defined on a peptide) and with the new release will come the ability to see if a fragment specifically supports one position over another.

**Comment by ArthurDeclercq** [comment]
thank you very much :D

**Comment by douweschulte** [comment]
I just made an alpha release, there are some tiny things that will introduce breaking changes in the coming weeks. The python automatic release just started so lets hope it is successful but if so you can use this release to work around the above panic message. If there is any more bindings you need please let us know so we can expand the Python bindings.

**Comment by douweschulte** [comment]
https://pypi.org/project/rustyms/0.9.0a1/ Seems to have worked!
