### ISSUE TITLE
Question: mass shift modification parsing

### ISSUE THREAD

**Issue by singjc** [rusteomics/mzcore#40]
Hi,

I am interested in using the rustyms library to extract information from modified peptides strings. If I have the following modified peptide seuqence (with a mass shift): "KDM[+15.9949]YGLQAEME". Would it be possible read this string and then derive the type of modfication and the amino acid, "Oxidation@M"? 

Best,

Justin

**Comment by douweschulte** [comment]
Hi Justin. If you use the provided ProForma parsers you will end up with a modification of that specified mass. Changing this mass modification to a database modification (Oxidation from Unimod) is something I have some internal code for (also used for reading of identified peptides files) so I could make that function public. Doing it this way will have a very minor effect on the peptide though as the mass is close enough to the monoisotopic mass that most functions will already work fine. 

If you are interested here is the current function, I am thinking of adding the tolerance as a parameter and then making it public.
```rust
/// Look at the provided modifications and see if they match any modification on this peptide with
/// more information and replace those. Replaces any mass modification within 0.1 Da or any precise
/// matching formula with the provided modifications.
pub(crate) fn inject_modifications(&mut self, modifications: &[SimpleModification]) {}
```

**Comment by singjc** [comment]
Hi Douwe,

Thank you for the info, the `LinearPeptide` ProForma parser works great!

I think it would be great if you add a tolerance and make the `inject_modifications` method public, that would be useful!

I played around with the LinearPeptide parser to get the desired output I want. Not sure if the code is optimal or could be written better, but it seems to work.

```rust
fn get_modification_name_site(
      mod_search: ModificationSearchResult,
      modified_aa: AminoAcid,
  ) -> Option<String> {
      match mod_search {
          ModificationSearchResult::Mass(_, _, matches) => {
              matches
                  .into_iter()
                  .find_map(
                      |(ontology, _, _, modification)| match (ontology, modification) {
                          (
                              Ontology::Unimod,
                              Modification::Predefined(_, specificities, _, psims_name, _),
                          ) => specificities.iter().find_map(|specificity| {
                              if let PlacementRule::AminoAcid(amino_acids, _) = specificity {
                                  if amino_acids.contains(&modified_aa) {
                                      Some(format!("{}@{}", psims_name, modified_aa.char()))
                                  } else {
                                      None
                                  }
                              } else {
                                  None
                              }
                          }),
                          _ => None,
                      },
                  )
          }
          _ => None,
      }
  }

fn get_all_modifications(peptide: &LinearPeptide, tol_ppm: f64) -> String {
    let tol = Tolerance::new_ppm(tol_ppm);

    peptide
        .sequence
        .iter()
        .enumerate()
        .filter_map(|(_, sequence_element)| {
            sequence_element.modifications.first().and_then(|mod_mass| {
                let modified_aa = sequence_element.aminoacid;
                let mod_search = Modification::search(mod_mass, tol);

                get_modification_name_site(mod_search, modified_aa)
            })
        })
        .collect::<Vec<String>>()
        .join(";")
}
```

Use

```rust
let peptide_str = "MSFNELT[79.9663]ESNKKSLM[+15.9949]E";
let peptide = LinearPeptide::pro_forma(peptide_str).unwrap();
let result = get_all_modifications(&peptide, 1.0);
println!(
    "Found the following modifications {} for {}",
    result, peptide_str
);
```

output

```
Found the following modifications Phospho@T;Oxidation@M for MSFNELT[79.9663]ESNKKSLM[+15.9949]E
```

**Comment by douweschulte** [comment]
Looks nice. There are some caveats with multiple modifications and the like but the intent is clear. There is a major difference between this and function I provided. As the later one is focussed on allowing you to provide a list of modifications that (could) occur in the given peptide, potentially known by some other source. While the function you wrote for all unknown modifications (as in one where only the mass is known) searches for the closest modification in unimod. This could be a great way of adding meaning to the peptide, but it might also misattribute a mass to something else. If I would write a similar method I would give the caller the following parameters: tolerance, ontologies to pick modifications from, `force_closest` which forces the closest modification if multiple are found within the same tolerance (still unclear if there are multiple with exactly the same distance). Potentially chemical formulas could also be replaced, but the need for that might be lower.

Something like this function is very possible to be written, I am a tiny bit hesitant on one point though. This function would add information (the name of the modification, and so possible pathways of how it got there etc) where none is available. So it would help me if you could point out what you would use this function for.

**Comment by singjc** [comment]
> Looks nice. There are some caveats with multiple modifications and the like but the intent is clear. There is a major difference between this and function I provided. As the later one is focussed on allowing you to provide a list of modifications that (could) occur in the given peptide, potentially known by some other source. While the function you wrote for all unknown modifications (as in one where only the mass is known) searches for the closest modification in unimod. This could be a great way of adding meaning to the peptide, but it might also misattribute a mass to something else. If I would write a similar method I would give the caller the following parameters: tolerance, ontologies to pick modifications from, `force_closest` which forces the closest modification if multiple are found within the same tolerance (still unclear if there are multiple with exactly the same distance). Potentially chemical formulas could also be replaced, but the need for that might be lower.
> 
> Something like this function is very possible to be written, I am a tiny bit hesitant on one point though. This function would add information (the name of the modification, and so possible pathways of how it got there etc) where none is available. So it would help me if you could point out what you would use this function for.

Thank you for the information. I think those are good points. My purpose for having a function that can take a peptide sequence with mass shifts and return a string of a potential PSI name and the corresponding amino acid is for prediction models. I am currently working with AlphaPeptDeep's prediction models. I currently have implemented the retention time prediction model in Rust. The required inputs for these models are:

- The naked peptide string (e.g., "MSFNELT[79.9663]ESNKKSLM[+15.9949]E")
- Modification sites (e.g., "7;15")
- Modification names and residues (e.g., "Phospho@T;Oxidation@M")

I use Sage to identify PSMs (Peptide-Spectrum Matches), and then use the output peptide sequences, which contain mass shifts, to make predictions.

I currently use a [tsv file](https://raw.githubusercontent.com/MannLabs/alphabase/main/alphabase/constants/const_files/modification.tsv) that contains this information. But I was thinking it would be nice to not rely on the TSV file and to generate these on the fly.

| mod_name | unimod_mass | unimod_avge_mass | composition | unimod_modloss | modloss_composition | classification | unimod_id | smiles | modloss_importance |
|----------|-------------|-------------------|-------------|----------------|---------------------|-----------------|-----------|--------|---------------------|
| Acetyl@T | 42.010565 | 42.0367 | H(2)C(2)O(1) | 0.0 | | Post-translational | 1 | | 0.0 |
| Acetyl@Protein_N-term | 42.010565 | 42.0367 | H(2)C(2)O(1) | 0.0 | | Post-translational | 1 | C(=O)C | 0.0 |
| Acetyl@S | 42.010565 | 42.0367 | H(2)C(2)O(1) | 0.0 | | Post-translational | 1 | | 0.0 |
| Acetyl@C | 42.010565 | 42.0367 | H(2)C(2)O(1) | 0.0 | | Post-translational | 1 | | 0.0 |

**Comment by douweschulte** [comment]
Adding back in the modifications names after running analysis in Sage sounds like a good use of such a feature. Internally the `inject_modifications` was used very similarly, namely to get named modifications out of peaks file. 

I made a new implementation of this function which allows over much more control on the matching itself and should be considerably faster if used for many peptides after each other. It can do the following replacements:

| From | To |
| --- | --- |
| MSFNELT[79.9663]ESNKKSLM[+15.9949]E | MSFNELT[Phospho]ESNKKSLM[Oxidation]E |
| Q[-17.02655]NKKSLM[+15.9949]E | [Gln->pyro-glu]-QNKKSLM[Oxidation]E |
| M[Formula:O1]KSLM[+15.9949]E | M[Oxidation]KSLM[Oxidation]E |

And here is a quick example on how to use it:
```rust
let mut search = PeptideModificationSearch::in_ontologies(vec![Ontology::Unimod], None).replace_formulas(true);
let peptide = LinearPeptide::pro_forma("MSFNELT[79.9663]ESNKKSLM[+15.9949]E", None).unwrap();
let expected = LinearPeptide::pro_forma("MSFNELT[Phospho]ESNKKSLM[Oxidation]E", None).unwrap();
assert_eq!(search.search(peptide), expected);
```

It will handle multiple modifications, ambiguous modification, n/c terminal modifications, modifications that can only be on n/c but are placed on the side chain (see example 2) and labile modifications. Control is given over the tolerance, mass mode, strategy when multiple modifications are possible, terminal redefinition (see example 2), and whether to replace formulas. This structure can be made with either a list of predefined modifications, eg peaks gives a column of all mod that are present on that peptide, or a list of ontologies to search in.

This will not directly give you the table, but it will give you all information you need to generate that. I did see however that you used the unimod chemical formula notation, would it be helpful if rustyms can directly output that or are you fine with the ProForma format?

And lastly, if you feel like any of the predictions you made would be fitting in rustyms feel free to discuss, I would be happy to have RT prediction provided for example.
